name: "Static analysis of the code and testing"
description: "A composite action to run static analysis and unit tests for a Java project."


runs:
  using: "composite"
  steps:
    - name: Run Checkstyle Analysis
      run: echo "my custom action"
      shell: bash
